### ISSUE TITLE
"Invalid module format" in 14.04

### ISSUE THREAD

**Issue by ElSebita** [Alamot/3dsp#4]
Trying your drivers on Xubuntu 14.04 with an Argentinian netbook.
3DSP uWB and 3DSP WiFi Radar both start but there's no WLAN hardware available.
boot.log says
```
insmod: ERROR: could not insert module /usr/local/3DSP/usb/3dspusbbus.ko: Invalid module format"
```
for all modules (3dspusbwlanpriv.ko, 3dspusbwlan.ko, 3dspusbbtpriv.ko, 3dspusbbt.ko).

**Comment by marlontrujillo1080** [comment]
Do you resolve that issue? I have the same problem in my lubuntu...

**Comment by Alamot** [comment]
No, sorry. I tried to install lubuntu in my system to test it, but I faced it multiple problems. But I installed the Linux Lite 2.2 (based on Ubuntu 14.04 LTS and featuring the Xfce desktop) and the wifi driver works successfully. Maybe you could try this distro.

**Comment by marlontrujillo1080** [comment]
Great, i gonna try and talk you back.

**Comment by marlontrujillo1080** [comment]
Done. It Works!

**Comment by ElSebita** [comment]
I finally ditched Xubuntu and replaced it with Linux Lite as you suggested. Your modules NOW WORK nicely. So it's something on Xubuntu that bothers. Strangely, both share the same Ubuntu base. Well, filed for knowledge.
