### ISSUE TITLE
What about ArchLinux?

### ISSUE THREAD

**Issue by nicolasdanelon** [Alamot/3dsp#5]
What needs to be done to make the driver work well in ArchLinux?
btw nice work!

**Comment by Alamot** [comment]
Unfortunately I have no experience with ArchLinux and no free time this period. Did you try to compile the driver (run 'make clean' inside the folder 3dsp/driver_src)? Are there any error messages?

**Comment by nicolasdanelon** [comment]
Here we go!!

[nicolasm@net-troz driver_src]$ pwd
/home/nicolasm/wifi/3dsp/driver_src

[nicolasm@net-troz driver_src]$ make clean
make -C /lib/modules/3.16.7.3-1-MANJARO/build/ M=`pwd` clean
make[1]: Entering directory '/usr/lib/modules/3.16.7.3-1-MANJARO/build'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/3.16.7.3-1-MANJARO/build'
Makefile:28: recipe for target 'clean' failed

[nicolasm@net-troz driver_src]$ make
make -C /lib/modules/3.16.7.3-1-MANJARO/build/ M=`pwd`
make[1]: Entering directory '/usr/lib/modules/3.16.7.3-1-MANJARO/build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/usr/lib/modules/3.16.7.3-1-MANJARO/build'
Makefile:15: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nicolasdanelon** [comment]
tell me what to do and I'll try to meke it work :) 
is there any pdf out there to read about this thigs?

**Comment by Alamot** [comment]
Hmmm.... Sorry, I have no idea what's wrong. 
I suggest you ask to arch forums for more infos on the subject.

**Comment by Alamot** [comment]
I think that you have to install the kernel headers. Search how you do that in Arch. I have no idea.

**Comment by nicolasdanelon** [comment]
All right. Thanks! :)
