### ISSUE TITLE
install on linux lite 2.2

### ISSUE THREAD

**Issue by kbsao5** [Alamot/3dsp#6]
I'm unable to install it on linux lite 2.2.
3.13.0-24 kernel-generic.
Always gives error while installing ..
He even install the program, but only gets unplug the option ..
and the wifi-radar shows "no valid wireless device!"

**Comment by Alamot** [comment]
Can you run 'make clean' and 'make' inside the folder 3dsp/driver_src and tell me if it outputs some errors?
